"use client";
import { useState, type FormEvent } from 'react';
import Image from 'next/image';
import Link from 'next/link';
export default function ContactForm(){
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [reference,setReference]=useState('');const [copied,setCopied]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');try{const fields=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,consent:fields.consent==='on'})});const data=await response.json();if(!response.ok)throw Error(data.message);setReference(data.reference);setMessage(data.message);}catch(error){setMessage(error instanceof Error?error.message:'Your message could not be sent. Please try again.');}finally{setBusy(false)}}
 return <main className="catalogue-shell contact-page"><section className="contact-layout"><div className="contact-introduction"><p className="eyebrow">CONTACT RRFIN</p><h1>Let’s talk about<br />your next move.</h1><p>Ask about vehicle finance, a second-hand listing or an existing enquiry. Share the details and our company team will contact you soon.</p><Image src="/images/finance.webp" width={800} height={500} alt="Illustrative finance consultation" /><div className="contact-reference-info"><h2>One enquiry. Your own reference.</h2><p>Every submitted message receives a unique reference number. Keep it for follow-ups with our team.</p><Link href="/apply">Ready to apply for vehicle finance? ↗</Link></div></div><div className="marketplace-form contact-form">{reference?<div className="contact-success" role="status"><span className="eyebrow">ENQUIRY RECEIVED</span><h2>Thank you for contacting us.</h2><p>{message}</p><span>Your reference number</span><strong>{reference}</strong><button className="button button-primary" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(reference);setCopied(true);}catch{setCopied(false);}}}>{copied?'Reference copied':'Copy reference'}</button><p>Save this number and quote it when following up.</p><button className="button button-secondary" type="button" onClick={()=>{setReference('');setMessage('');setCopied(false);}}>Send another enquiry</button></div>:<form onSubmit={submit}><h2>Mail us</h2><p>Your message goes privately to our company team.</p><div className="marketplace-fields"><label>Full name *<input name="name" required maxLength={150} autoComplete="name" placeholder="Your full name" /></label><label>Email address *<input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="you@example.com" /></label><label>Mobile number (optional)<input name="mobile" type="tel" inputMode="numeric" pattern="[6-9][0-9]{9}" maxLength={10} autoComplete="tel-national" placeholder="10-digit Indian mobile number" /></label><label>Existing reference (optional)<input name="reference" maxLength={100} placeholder="Application or vehicle enquiry reference" /></label></div><label>Subject *<input name="subject" required maxLength={150} placeholder="How can we help?" /></label><label>Your message *<textarea name="message" rows={5} required maxLength={4000} placeholder="Tell us about your vehicle, finance question or enquiry." /></label><label className="consent-label"><input name="consent" type="checkbox" required />I agree to share these details with the company team and be contacted about my enquiry.</label>{message&&<p role="alert">{message}</p>}<button type="submit" className="button button-primary" disabled={busy}>{busy?'Sending your message…':'Send message & generate reference ↗'}</button><p className="fine-print">Your reference number will appear after your enquiry is received.</p></form>}</div></section></main>;
}
