const { test } = require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const ts=require('typescript');
function handler({mailFailure=false,rateAllowed=true}={}){
 const source=fs.readFileSync(path.join(__dirname,'../app/api/contact/route.ts'),'utf8');const writes=[];const messages=[];
 const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;const exports={};
 const sandbox={exports,require(name){if(name==='node:crypto')return require(name);if(name.includes('marketplace/store'))return {sameOrigin:r=>r.headers.get('origin')===new URL(r.url).origin,rateLimit:async()=>rateAllowed,write:async(p,data)=>writes.push({p,data})};if(name.includes('marketplace/mail'))return {adminMail:async(subject,text)=>{if(mailFailure)throw Error('Temporary mail failure');messages.push({subject,text});}};throw Error(name);},Response,Date,Intl,console:{error(){} }};
 vm.runInNewContext(output,sandbox);return {post:exports.POST,writes,messages};
}
const payload={name:'Test enquiry',email:'fixture@example.invalid',mobile:'',subject:'Vehicle question',reference:'RELATED-REF',message:'Please discuss the vehicle.',consent:true};
const request=(body,origin='https://rrfin.test')=>new Request('https://rrfin.test/api/contact',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
test('contact generates a reference, saves private enquiry, and includes reference in company mail',async()=>{const h=handler();const response=await h.post(request(payload));assert.equal(response.status,201);const data=await response.json();assert.match(data.reference,/^RRFIN-\d{8}-[A-F0-9]{12}$/);assert.equal(h.writes.at(-1).data.notification,'sent');assert.equal(h.writes[0].data.relatedReference,'RELATED-REF');assert.ok(h.messages[0].text.includes(data.reference));assert.ok(h.messages[0].text.includes(payload.email));});
test('saved reference survives a temporary email failure for administrator follow-up',async()=>{const h=handler({mailFailure:true});const response=await h.post(request(payload));assert.equal(response.status,201);assert.equal(h.writes.at(-1).data.notification,'failed');assert.ok((await response.json()).reference);});
test('invalid inputs, missing consent, foreign origin and rapid repeats create no enquiry',async()=>{for(const body of [null,{...payload,email:'invalid'},{...payload,consent:false},{...payload,subject:''}]){const h=handler();assert.equal((await h.post(request(body))).status,400);assert.equal(h.writes.length,0);}const h=handler();assert.equal((await h.post(request(payload,'https://other.test'))).status,403);assert.equal(h.writes.length,0);const limited=handler({rateAllowed:false});assert.equal((await limited.post(request(payload))).status,429);assert.equal(limited.writes.length,0);});
