const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
const root=require('node:path').join(__dirname,'../');
function load(file,mocks){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(root+file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,require:n=>mocks[n]||require(n),Response,Date,Number});return exports;}
const reviewModule=load('lib/reviews.ts',{});
const item={id:'fixture',name:'Customer',service:'Car finance',rating:5,feedback:'Clear communication throughout.',createdAt:new Date().toISOString(),status:'pending',private:{email:'private@example.invalid'}};
function handler(allowed=true){const writes=[];const rows=[item,{...item,id:'public',status:'approved'},{...item,id:'rejected',status:'rejected'}];const h=load('app/api/reviews/route.ts',{'@/lib/reviews':reviewModule,'@/lib/marketplace/store':{records:async()=>rows,write:async(p,d)=>writes.push(d),sameOrigin:r=>r.headers.get('origin')===new URL(r.url).origin,rateLimit:async()=>allowed}});return {...h,writes};}
const body={name:'Customer',email:'private@example.invalid',service:'Car finance',rating:5,feedback:'Clear communication throughout.',consent:true};
const request=(data,origin='https://test.invalid')=>new Request('https://test.invalid/api/reviews',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(data)});
test('only approved reviews are public and email is never returned',async()=>{const response=await handler().GET();const data=await response.json();assert.equal(data.reviews.length,1);assert.equal(data.reviews[0].id,'public');assert.equal(JSON.stringify(data).includes('private'),false);assert.equal(JSON.stringify(data).includes('email'),false);});
test('new reviews are saved pending with private contact details',async()=>{const h=handler();assert.equal((await h.POST(request(body))).status,201);assert.equal(h.writes[0].status,'pending');assert.equal(h.writes[0].private.email,body.email);});
test('invalid rating, missing consent, foreign origin and rapid repeats cannot publish',async()=>{for(const data of [{...body,rating:6},{...body,rating:3.5},{...body,consent:false},{...body,email:'bad'},{...body,feedback:'short'}]){const h=handler();assert.equal((await h.POST(request(data))).status,400);assert.equal(h.writes.length,0);}assert.equal((await handler().POST(request(body,'https://other.invalid'))).status,403);assert.equal((await handler(false).POST(request(body))).status,429);});

