import 'server-only';
import * as cheerio from 'cheerio';
import { manufacturerSources } from '../manufacturers';
import { brandDirectory } from '../brand-directory';
import { emptyModel, emptyVariant, makeImage } from './utils';
import type { VehicleModel, VehicleType, VehicleVariant } from '../types';

const catalogueRoots: Record<string,string> = { toyota:'https://www.toyotabharat.com/', hyundai:'https://www.hyundai.com/in/en/find-a-car', bentley:'https://www.bentleymotors.com/en/models.html' };
const clean=(text:unknown)=>typeof text==='string'?text.replace(/\s+/g,' ').trim():'';
const memo=new Map<string,{expires:number;promise:Promise<VehicleModel[]>}>();
function hosts(id:string){const source=manufacturerSources.find(s=>s.id===id);if(!source)throw Error('Unknown manufacturer.');return [source.officialUrl,source.vehicleUrl,source.priceUrl,catalogueRoots[id]].filter(Boolean).map(u=>new URL(u!).hostname.replace(/^www\./,''));}
function allowed(url:string,id:string){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password&&hosts(id).some(h=>u.hostname===h||u.hostname.endsWith('.'+h));}catch{return false;}}
async function page(url:string,id:string){if(!allowed(url,id))throw Error('Unsupported manufacturer source.');let current=url;for(let step=0;step<4;step++){const response=await fetch(current,{redirect:'manual',signal:AbortSignal.timeout(12000),headers:{'User-Agent':'RRFIN-ManufacturerCatalogue/1.0',Accept:'text/html,application/json'},cache:'no-store'});if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');if(!location)throw Error('Invalid manufacturer response.');current=new URL(location,current).href;if(!allowed(current,id))throw Error('Unsupported manufacturer redirect.');continue;}if(!response.ok)throw Error('Manufacturer data is unavailable.');if(Number(response.headers.get('content-length')||0)>4000000)throw Error('Manufacturer response too large.');const reader=response.body?.getReader();if(!reader)throw Error('Empty manufacturer response.');const chunks:Uint8Array[]=[];let size=0;while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>4000000){await reader.cancel();throw Error('Manufacturer response too large.');}chunks.push(part.value);}return Buffer.concat(chunks).toString('utf8');}throw Error('Manufacturer redirect limit reached.');}
function absolute(value:string,base:string){try{const u=new URL(value,base);return u.protocol==='https:'?u.href:undefined;}catch{return undefined;}}
export async function manufacturerModels(id:string,category:VehicleType):Promise<VehicleModel[]>{
 const key=`${id}:${category}`;const cached=memo.get(key);if(cached&&cached.expires>Date.now())return cached.promise;
 const promise=(async()=>{const source=manufacturerSources.find(s=>s.id===id);if(!source)throw Error('Unknown manufacturer.');const url=catalogueRoots[id]||source.vehicleUrl||source.officialUrl;const $=cheerio.load(await page(url,id));const models=new Map<string,VehicleModel>();
 $('a[href]').each((_,node)=>{const href=absolute($(node).attr('href')||'',url);if(!href||!allowed(href,id))return;const path=new URL(href).pathname;
  const valid=id==='toyota'?/^\/showroom\/[^/]+\/(?:index-(?:fortuner|legender)\.html)?$/.test(path):id==='hyundai'?/^\/in\/en\/find-a-car\/(?:[^/]+\/highlights|taxi\/[^/]+)$/.test(path):/\/(?:models|vehicles|cars|motorcycles)\/[^/]+(?:\/[^/]+)?(?:\.html)?\/?$/.test(path);
  const name=clean($(node).attr('data-model-name')||$(node).text()||$(node).find('img').attr('alt'));
  if(!valid||!name||name.length>65||/^(?:know more|explore|discover|view|all models|models|configure|learn more|book|buy|read|test)/i.test(name)||models.has(href))return;
  const model=emptyModel(id,name,href,category);const img=$(node).find('img').first();const image=absolute(img.attr('data-src')||img.attr('src')||'',url);if(image&&/\.(?:webp|png|jpe?g)(?:\?|$)/i.test(image))model.images=[makeImage(image,name,href)];models.set(href,model);
 });return [...models.values()].slice(0,80);})();memo.set(key,{expires:Date.now()+3600000,promise});try{return await promise;}catch(error){memo.delete(key);throw error;}
}
export async function manufacturerModelDetails(id:string,model:VehicleModel):Promise<VehicleModel>{
 const html=await page(model.officialUrl,id);const $=cheerio.load(html);const images=model.images.filter(image=>/\.(?:webp|png|jpe?g)(?:\?|$)/i.test(image.url));
 $('main img, #specifications img, img').each((_,node)=>{const img=$(node);const raw=img.attr('data-src')||img.attr('src')||'';const url=absolute(raw,model.officialUrl);if(!url||images.some(i=>i.url===url)||!/\.(?:webp|png|jpe?g)(?:\?|$)/i.test(url)||/logo|icon|sprite|\btitle\b|footer|dealer|thumbnail/i.test(url))return;const modelPath=new URL(model.officialUrl).pathname.split('/').filter(Boolean).find(p=>!['in','en','showroom','find-a-car','models','vehicles','cars','highlights'].includes(p));if(modelPath&&!url.toLowerCase().includes(modelPath.toLowerCase()))return;images.push(makeImage(url,clean(img.attr('alt'))||model.name,model.officialUrl));});
 const variants:VehicleVariant[]=[];
 // Manufacturer specification tabs bind each trim to its own feature values.
 $('[id] a[href^="#"]').each((_,node)=>{const name=clean($(node).text());const target=$(node).attr('href')?.slice(1);if(!target||!name||name.length>80)return;const panel=$('[id]').filter((_,e)=>$(e).attr('id')===target).first();if(!panel.find('.featureName').length||!name.toLowerCase().includes(model.name.toLowerCase()))return;const variant=emptyVariant(id,model.name,name,model.officialUrl);const specs:Record<string,string>={};panel.find('li').each((_,row)=>{const key=clean($(row).find('.featureName').first().text());const value=clean($(row).find('.featureData').first().text());if(key&&value&&key.length<120&&value.length<400&&value!=='-')specs[key]=value;});variant.specifications=specs;const parent=panel.parents('[role="tabpanel"]').last();const fuelId=parent.attr('id');if(fuelId&&/petrol|diesel|cng|electric/i.test(fuelId))variant.fuel=fuelId.toUpperCase();variant.images=images.slice(0,12);if(!variants.some(v=>v.name===name))variants.push(variant);});
 const specs:Record<string,string>={};
 $('table').each((_,table)=>{const rows=$(table).find('tr');const headings=$(rows[0]).children('th,td').map((_,e)=>clean($(e).text())).get();const isVariantTable=headings.length>=2&&headings.slice(1).some(h=>h&&h.length<40&&!/no product|features|specification/i.test(h));if(isVariantTable){headings.slice(1).forEach((heading,index)=>{if(!heading||heading.length>40||/no product|features|specification/i.test(heading))return;const variant=emptyVariant(id,model.name,heading,model.officialUrl);const details:Record<string,string>={};rows.slice(1).each((_,row)=>{const cells=$(row).children('th,td').map((_,e)=>clean($(e).text())).get();if(cells[0]&&cells[0].length<100&&cells[index+1]&&cells[index+1].length<400&&cells[index+1]!=='-')details[cells[0]]=cells[index+1];});if(Object.keys(details).length>=3&&!variants.some(v=>v.name===heading)){variant.specifications=details;variant.images=images.slice(0,12);variants.push(variant);}});}else rows.each((_,row)=>{const cells=$(row).children('th,td').map((_,e)=>clean($(e).text())).get();if(cells.length===2&&cells[0]&&cells[0].length<100&&cells[1]&&cells[1].length<300)specs[cells[0]]=cells[1];});});
 const glb=$('model-viewer[src]').first().attr('src');const model3dUrl=glb?absolute(glb,model.officialUrl):undefined;
 const spinImages=images.filter(i=>/\/(?:360|spin|rotation)\//i.test(i.url));
 return {...model,images:images.slice(0,24),variants:variants.length?variants:model.variants,specifications:{...model.specifications,...specs},model3dUrl:model3dUrl&&/\.glb(?:\?|$)/i.test(model3dUrl)?model3dUrl:undefined,rotationImages:spinImages.length>=12?spinImages:undefined};
}
export function manufacturerCategory(id:string){return brandDirectory.find(b=>b.id===id)?.category;}
